---
# tasks file for phpmyadmin
- name: create directory
  file:
    path: "{{ phpmyadmin_httpd_directory }}/phpmyadmin"
    state: directory
    owner: "{{ phpmyadmin_httpd_user }}"
    group: "{{ phpmyadmin_httpd_group }}"
    mode: "750"

- name: download and unpack software
  unarchive:
    src: "{{ phpmyadmin_archive }}"
    dest: "{{ phpmyadmin_httpd_directory }}/phpmyadmin/"
    remote_src: yes
    extra_opts: ['--strip-components=1']
  register: phpmyadmin_download_and_unpack_software
  until: phpmyadmin_download_and_unpack_software is succeeded
  retries: 3

- name: configure software
  template:
    src: config.inc.php.j2
    dest: "{{ phpmyadmin_httpd_directory }}/phpmyadmin/config.inc.php"
    owner: "{{ phpmyadmin_httpd_user }}"
    group: "{{ phpmyadmin_httpd_group }}"
    mode: "640"

- name: install requirements
  package:
    name: "{{ phpmyadmin_requirements }}"
    state: present
  notify:
    - restart httpd
  register: phpmyadmin_install_requirements
  until: phpmyadmin_install_requirements is succeeded
  retries: 3
